version: '3.9'

services:
  node1:
    image: cp-node-async
    command: python -u cp-node-async.py node1
    environment:
      - SAMPLE_START=0
      - SAMPLE_END=5000
      - DELAY=30
    env_file:
      - cp-exp.env
  node2:
    image: cp-node-async
    command: python -u cp-node-async.py node2
    environment:
      - SAMPLE_START=5000
      - SAMPLE_END=10000
      - DELAY=30
    env_file:
      - cp-exp.env
  node3:
    image: cp-node-async
    command: python -u cp-node-async.py node3
    environment:
      - SAMPLE_START=10000
      - SAMPLE_END=15000
      - DELAY=30
    env_file:
      - cp-exp.env
  node4:
    image: cp-node-async
    command: python -u cp-node-async.py node4
    environment:
      - SAMPLE_START=15000
      - SAMPLE_END=20000
      - DELAY=30
    env_file:
      - cp-exp.env
  node5:
    image: cp-node-async
    command: python -u cp-node-async.py node5
    environment:
      - SAMPLE_START=20000
      - SAMPLE_END=25000
      - DELAY=30
    env_file:
      - cp-exp.env
  node6:
    image: cp-node-async
    command: python -u cp-node-async.py node6
    environment:
      - SAMPLE_START=25000
      - SAMPLE_END=30000
      - DELAY=30
    env_file:
      - cp-exp.env
  node7:
    image: cp-node-async
    command: python -u cp-node-async.py node7
    environment:
      - SAMPLE_START=30000
      - SAMPLE_END=35000
      - DELAY=30
    env_file:
      - cp-exp.env
  node8:
    image: cp-node-async
    command: python -u cp-node-async.py node8
    environment:
      - SAMPLE_START=35000
      - SAMPLE_END=40000
      - DELAY=30
    env_file:
      - cp-exp.env
  node9:
    image: cp-node-async
    command: python -u cp-node-async.py node9
    environment:
      - SAMPLE_START=40000
      - SAMPLE_END=45000
      - DELAY=30
    env_file:
      - cp-exp.env
  node10:
    image: cp-node-async
    command: python -u cp-node-async.py node10
    environment:
      - SAMPLE_START=45000
      - SAMPLE_END=50000
      - DELAY=30
    env_file:
      - cp-exp.env
  node11:
    image: cp-node-async
    command: python -u cp-node-async.py node11
    environment:
      - SAMPLE_START=50000
      - SAMPLE_END=55000
      - DELAY=30
    env_file:
      - cp-exp.env
  node12:
    image: cp-node-async
    command: python -u cp-node-async.py node12
    environment:
      - SAMPLE_START=55000
      - SAMPLE_END=60000
      - DELAY=30
    env_file:
      - cp-exp.env
  node13:
    image: cp-node-async
    command: python -u cp-node-async.py node13
    environment:
      - SAMPLE_START=60000
      - SAMPLE_END=65000
      - DELAY=30
    env_file:
      - cp-exp.env
  node14:
    image: cp-node-async
    command: python -u cp-node-async.py node14
    environment:
      - SAMPLE_START=65000
      - SAMPLE_END=70000
      - DELAY=30
    env_file:
      - cp-exp.env
  node15:
    image: cp-node-async
    command: python -u cp-node-async.py node15
    environment:
      - SAMPLE_START=70000
      - SAMPLE_END=75000
      - DELAY=30
    env_file:
      - cp-exp.env
  node16:
    image: cp-node-async
    command: python -u cp-node-async.py node16
    environment:
      - SAMPLE_START=75000
      - SAMPLE_END=80000
      - DELAY=30
    env_file:
      - cp-exp.env
  node17:
    image: cp-node-async
    command: python -u cp-node-async.py node17
    environment:
      - SAMPLE_START=80000
      - SAMPLE_END=85000
      - DELAY=30
    env_file:
      - cp-exp.env
  node18:
    image: cp-node-async
    command: python -u cp-node-async.py node18
    environment:
      - SAMPLE_START=85000
      - SAMPLE_END=90000
      - DELAY=30
    env_file:
      - cp-exp.env
  node19:
    image: cp-node-async
    command: python -u cp-node-async.py node19
    environment:
      - SAMPLE_START=90000
      - SAMPLE_END=95000
      - DELAY=30
    env_file:
      - cp-exp.env
  node20:
    image: cp-node-async
    command: python -u cp-node-async.py node20
    environment:
      - SAMPLE_START=95000
      - SAMPLE_END=100000
      - DELAY=30
    env_file:
      - cp-exp.env
  node21:
    image: cp-node-async
    command: python -u cp-node-async.py node21
    environment:
      - SAMPLE_START=100000
      - SAMPLE_END=105000
      - DELAY=30
    env_file:
      - cp-exp.env
  node22:
    image: cp-node-async
    command: python -u cp-node-async.py node22
    environment:
      - SAMPLE_START=105000
      - SAMPLE_END=110000
      - DELAY=30
    env_file:
      - cp-exp.env
  node23:
    image: cp-node-async
    command: python -u cp-node-async.py node23
    environment:
      - SAMPLE_START=110000
      - SAMPLE_END=115000
      - DELAY=30
    env_file:
      - cp-exp.env
  node24:
    image: cp-node-async
    command: python -u cp-node-async.py node24
    environment:
      - SAMPLE_START=115000
      - SAMPLE_END=120000
      - DELAY=30
    env_file:
      - cp-exp.env

  myrabbitmq:
    image: rabbitmq:3.9
    volumes:
      - ./myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf

  main:
    image: cp-main-async
    command: python -u cp-main-async.py node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 node11 node12 node13 node14 node15 node16 node17 node18 node19 node20 node21 node22 node23 node24
    env_file:
      - cp-exp.env
    volumes:
      - ./log:/workspace/log
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9
      - node10
      - node11
      - node12
      - node13
      - node14
      - node15
      - node16
      - node17
      - node18
      - node19
      - node20
      - node21
      - node22
      - node23
      - node24
      - myrabbitmq
