version: '3.9'

services:
  node1:
    image: cp-node-async
    command: python -u cp-node-async.py node1
    environment:
      - SAMPLE_START=0
      - SAMPLE_END=3330
      - DELAY=30
    env_file:
      - cp-exp.env
  node2:
    image: cp-node-async
    command: python -u cp-node-async.py node2
    environment:
      - SAMPLE_START=3330
      - SAMPLE_END=6660
      - DELAY=30
    env_file:
      - cp-exp.env
  node3:
    image: cp-node-async
    command: python -u cp-node-async.py node3
    environment:
      - SAMPLE_START=6660
      - SAMPLE_END=9990
      - DELAY=30
    env_file:
      - cp-exp.env
  node4:
    image: cp-node-async
    command: python -u cp-node-async.py node4
    environment:
      - SAMPLE_START=9990
      - SAMPLE_END=13320
      - DELAY=30
    env_file:
      - cp-exp.env
  node5:
    image: cp-node-async
    command: python -u cp-node-async.py node5
    environment:
      - SAMPLE_START=13320
      - SAMPLE_END=16650
      - DELAY=30
    env_file:
      - cp-exp.env
  node6:
    image: cp-node-async
    command: python -u cp-node-async.py node6
    environment:
      - SAMPLE_START=16650
      - SAMPLE_END=19980
      - DELAY=30
    env_file:
      - cp-exp.env
  node7:
    image: cp-node-async
    command: python -u cp-node-async.py node7
    environment:
      - SAMPLE_START=19980
      - SAMPLE_END=23310
      - DELAY=30
    env_file:
      - cp-exp.env
  node8:
    image: cp-node-async
    command: python -u cp-node-async.py node8
    environment:
      - SAMPLE_START=23310
      - SAMPLE_END=26640
      - DELAY=30
    env_file:
      - cp-exp.env
  node9:
    image: cp-node-async
    command: python -u cp-node-async.py node9
    environment:
      - SAMPLE_START=26640
      - SAMPLE_END=29970
      - DELAY=30
    env_file:
      - cp-exp.env
  node10:
    image: cp-node-async
    command: python -u cp-node-async.py node10
    environment:
      - SAMPLE_START=29970
      - SAMPLE_END=33300
      - DELAY=30
    env_file:
      - cp-exp.env
  node11:
    image: cp-node-async
    command: python -u cp-node-async.py node11
    environment:
      - SAMPLE_START=33300
      - SAMPLE_END=36630
      - DELAY=30
    env_file:
      - cp-exp.env
  node12:
    image: cp-node-async
    command: python -u cp-node-async.py node12
    environment:
      - SAMPLE_START=36630
      - SAMPLE_END=39960
      - DELAY=30
    env_file:
      - cp-exp.env
  node13:
    image: cp-node-async
    command: python -u cp-node-async.py node13
    environment:
      - SAMPLE_START=39960
      - SAMPLE_END=43290
      - DELAY=30
    env_file:
      - cp-exp.env
  node14:
    image: cp-node-async
    command: python -u cp-node-async.py node14
    environment:
      - SAMPLE_START=43290
      - SAMPLE_END=46620
      - DELAY=30
    env_file:
      - cp-exp.env
  node15:
    image: cp-node-async
    command: python -u cp-node-async.py node15
    environment:
      - SAMPLE_START=46620
      - SAMPLE_END=49950
      - DELAY=30
    env_file:
      - cp-exp.env
  node16:
    image: cp-node-async
    command: python -u cp-node-async.py node16
    environment:
      - SAMPLE_START=49950
      - SAMPLE_END=53280
      - DELAY=30
    env_file:
      - cp-exp.env
  node17:
    image: cp-node-async
    command: python -u cp-node-async.py node17
    environment:
      - SAMPLE_START=53280
      - SAMPLE_END=56610
      - DELAY=30
    env_file:
      - cp-exp.env
  node18:
    image: cp-node-async
    command: python -u cp-node-async.py node18
    environment:
      - SAMPLE_START=56610
      - SAMPLE_END=60000
      - DELAY=30
    env_file:
      - cp-exp.env

  myrabbitmq:
    image: rabbitmq:3.9
    volumes:
      - ./myrabbit.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf

  main:
    image: cp-main-async
    volumes:
      - ./async-logs:/workspace/log
    command: python -u cp-main-async.py node1 node2 node3 node4 node5 node6 node7 node8 node9 node10 node11 node12 node13 node14 node15 node16 node17 node18
    env_file:
      - cp-exp.env
    volumes:
      - ./log:/workspace/log
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9
      - node10
      - node11
      - node12
      - node13
      - node14
      - node15
      - node16
      - node17
      - node18
      - myrabbitmq
